<?php


namespace App\ELMOHRSuite\Apps\AwardApp\Providers;


use App\ELMOHRSuite\Apps\AwardApp\Services\AwardService;
use App\ELMOHRSuite\Core\Providers\AbstractServiceProvider;


class AwardsServiceProvider extends AbstractServiceProvider
{
    public function getSlackRoute()
    {
        return __DIR__ . '/../Routes/slack.php';
    }

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        $this->app->bind(
            'AwardService',
            AwardService::class
        );
    }
}